typography_spectrum: 0.43994674691930413
color:
  brandStrength: 0.3702047204133123
  lightness: 0.7095180270262063
  saturation: 0.44407271570526063
  rhythmicContrast: 0.6200665852520615
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
layout_spectrum: 0.8238165252842009
name: CR_SE
navigation:
  - name: CRSE Videoproduction
    url: 'http://www.vimeo.com/crse'
    type: external
  - name: CRSE photography
    url: 'https://500px.com/cr_se'
    type: external
title: '#CR_SE'
description: journey to self
