title: '#CR_SE'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
color:
  saturation: 0.6714175480883569
  brandStrength: 0.2814492210745811
  rhythmicContrast: 0.8335507235024124
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.6571111844386905
typography_spectrum: 0.6310419
description: ''
navigation:
  - name: CRUSE videography
    url: 'http://www.vimeo.com/crse'
    type: external
  - name: CRUSE photography
    url: 'https://500px.com/cr_se'
    type: external
  - name: CRUSE on facebook
    url: 'https://www.facebook.com/cruse.io/'
    type: external
  - name: CRUSE on instagram
    url: 'https://www.instagram.com/cr_se/'
    type: external
  - name: CRUSE on LinkedIn
    url: 'https://de.linkedin.com/in/christian-kruse-5b330920'
    type: external
layout_spectrum: 0.5204082
name: CR_SE
