typography_spectrum: 0.5201562782749534
color:
  brandStrength: 0.28144922107458115
  lightness: 0.6571111844386905
  saturation: 0.6714175480883569
  rhythmicContrast: 0.8335507235024124
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.46663745678961277
name: CR_SE
navigation:
  - name: CRSE videoproduction
    url: 'http://www.vimeo.com/crse'
    type: external
  - name: CRSE photography
    url: 'https://500px.com/cr_se'
    type: external
title: '#CR_SE'
description: journey to self
