title: '#CR_SE'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.1455424
  brandStrength: 0.3711063
  lightness: 1
  brandColors:
    - '#030207'
    - '#D9E7F4'
    - '#6088CD'
    - '#455F80'
    - '#608245'
  rhythmicContrast: 0.8555317
typography_spectrum: 0.1584318
description: journey to self
navigation:
  - name: Videoproduction
    url: 'http://vimeo.com/dynamicfeatures'
    type: external
layout_spectrum: 0.5504833
name: CR_SE
