title: '#CR_SE'
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.6714175480883569
  brandStrength: 0.2814492210745811
  rhythmicContrast: 0.8335507235024124
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  lightness: 0.6571111844386905
typography_spectrum: 0.5201562782749534
description: journey to self
navigation:
  - name: CRSE videoproduction
    url: 'http://www.vimeo.com/crse'
    type: external
  - name: CRSE photography
    url: 'https://500px.com/cr_se'
    type: external
layout_spectrum: 1
name: CR_SE
